### ISSUE TITLE
[Android Bootcamp] Project 2: Grid ImageSearch - Ready for Review

### ISSUE THREAD

**Issue by shz117** [shz117/ImageSearch#1]
My app is complete, please review. /cc @codepathreview @codepath

**Comment by codepathreview** [comment]
:+1: Looks good overall. Great work on getting so many optionals done, hope that gives you more familiarity with concepts of Android development. 

I have provided a detailed [Project 2 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. The next assignment (Twitter Client) will be very important since it introduces the majority of the remaining pieces necessary to build a fully functional API client with complex feeds of data and user creation.
